services:
  # API Service (Laravel PHP)
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: api-backend
    volumes:
      - ./packages/api:/var/www/api
      - ./packages/api/vendor:/var/www/api/vendor
      - ./packages/api/.env:/var/www/api/.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000']
      interval: 10s
      timeout: 5s
      retries: 3

  # Admin Panel (React + Vite)
  admin:
    build:
      context: ./packages/web-admin
      dockerfile: Dockerfile
    container_name: admin-frontend
    volumes:
      - ./packages/web-admin:/var/www/admin
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5173:80"
    restart: unless-stopped

  # Web Front (React + Vite)
  web:
    build:
      context: ./packages/web-front
      dockerfile: Dockerfile
    container_name: web-frontend
    volumes:
      - ./packages/web-front:/var/www/front
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5174:80"
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: u2478981_medicare
      MYSQL_USER: u2478981_default
      MYSQL_PASSWORD: Om5LQ8rgyUym9V26
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:

networks:
  default:
    driver: bridge