version: '3.8'

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: api-backend
    volumes:
      - ./packages/api:/var/www/api
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  admin:
    build:
      context: ./packages/web-admin
      dockerfile: Dockerfile
    container_name: admin-frontend
    volumes:
      - ./packages/web-admin:/var/www/admin
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5174:80"
    restart: unless-stopped

  web:
    build:
      context: ./packages/web-front
      dockerfile: Dockerfile
    container_name: web-frontend
    volumes:
      - ./packages/web-front:/var/www/front
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5173:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge