version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    container_name: api-backend
    volumes:
      - ./packages/api:/var/www/api
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  admin:
    build:
      context: .
      dockerfile: packages/web-admin/Dockerfile
    container_name: admin-frontend
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5174:80"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: packages/web-front/Dockerfile
    container_name: web-frontend
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - "5173:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge