version: '3.8'

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: api-backend
    volumes:
      - ./packages/api:/var/www/api
      - /var/www/api/vendor
      - /etc/letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: '10mb'
        max-file: '1'
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - 8000:8000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', 'http://0.0.0.0:8000']
      interval: 10s
      timeout: 3s
  admin:
    build:
      context: ./packages/web-admin
      dockerfile: Dockerfile
    container_name: admin-frontend
    volumes:
      - ./packages/web-admin:/var/www/admin
      - /var/www/admin/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: '10mb'
        max-file: '1'
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - 5173
    restart: unless-stopped
  web:
    build:
      context: ./packages/web-front
      dockerfile: Dockerfile
    container_name: web-frontend
    volumes:
      - ./packages/web-front:/var/www/front
      - /var/www/front/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: '10mb'
        max-file: '1'
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - 5173:80
    restart: unless-stopped

networks:
  default:
    external: true
    name: medicare
