name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run deploy script on server with password
        run: |
          sshpass -p "cPe4!uQshbHT" ssh -o StrictHostKeyChecking=no root@83.222.23.106 << EOF
            
          
            cd medicare-samite
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
          EOF
