name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: sudo apt-get install sshpass -y

      - name: Deploy to VPS
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@82.202.128.127 << 'EOF'
            set -e
            cd /root/medicare

            echo "Pulling latest changes..."
            git pull origin main

            echo "Stopping old containers..."
            docker-compose down

            echo "Building and starting fresh containers..."
            docker-compose build --no-cache

            echo "Cleaning up unused Docker resources..."
            docker-compose up -d

            echo "Deployment done successfully!"
          EOF