name: Build and Deploy with Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 83.222.23.106
          username: root
          password: cPe4!uQshbHT
          port: 22
          script: |
            cd /var/www
            git clone cooperation@samit.global 
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
