name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/otabek0302/medicare-samite.git
          cd medicare-samite

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Run deploy script on server with password
        run: |
          sshpass -p "cPe4!uQshbHT" ssh -t root@83.222.23.106 << EOF
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
          EOF
