name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository manually
        run: |
          git clone https://github.com/otabek0302/medicare-samite.git
          cd medicare-samite

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy files to server
        run: |
          sshpass -p cPe4!uQshbHT rsync -avz --exclude '.git*' ./ root@83.222.23.106:/path/to/target/directory/

      - name: Run commands on the server
        run: |
          sshpass -p cPe4!uQshbHT ssh root@83.222.23.106 << EOF
            cd /path/to/target/directory/
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
          EOF
