name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy files to server
        run: |
          sshpass -p cPe4!uQshbHT rsync -avz --exclude '.git*' ./ root@83.222.23.106:/var/www/html/

      - name: Run commands on the server
        run: |
          sshpass -p  cPe4!uQshbHT  ssh root@83.222.23.106 << EOF
            cd /var/www/html/
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
          EOF
