name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: gitlab-runner

      - name: Pull latest changes
        run: git pull origin main

      - name: Change to project directory
        run: cd $PROJECT_FOLDER

      - name: Restart Docker containers
        run: |
          docker-compose down
          docker-compose up --build -d
          docker system prune -f
