name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Restart Docker containers
        working-directory: ${{ github.workspace }}
        run: |
          docker-compose up --pull always --build -d
          docker system prune -f --volumes
