name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run a Test Command
        run: echo "Runner is working!"
